# Generated by Django 3.0.3 on 2020-02-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clones', '0002_auto_20200216_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='boardlist',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
